kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  # any feature gate can be enabled here with "Name": true
  # or disabled here with "Name": false
  # not all feature gates are tested, however
  "ContainerCheckpoint": true
nodes:
  - kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          criSocket: unix:///run/crio/crio.sock
          kubeletExtraArgs:
            cgroup-driver: cgroupfs
#  - role: worker
#    kubeadmConfigPatches:
#      - |
#        kind: JoinConfiguration
#        nodeRegistration:
#          criSocket: unix:///run/crio/crio.sock
#          kubeletExtraArgs:
#            cgroup-driver: cgroupfs
#  - role: worker
#    kubeadmConfigPatches:
#      - |
#        kind: JoinConfiguration
#        nodeRegistration:
#          criSocket: unix:///run/crio/crio.sock
#          kubeletExtraArgs:
#            cgroup-driver: cgroupfs